# Generated by Django 5.0.1 on 2024-01-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ditaresource', '0002_specialist_alter_client_email_alter_client_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
