# Generated by Django 5.0.1 on 2024-01-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ditaresource', '0003_issue_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
    ]
