# Generated by Django 5.0.1 on 2024-01-27 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ditaresource', '0005_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datee', models.DateField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ditaresource.tutor')),
            ],
        ),
    ]
