# Generated by Django 5.0.1 on 2024-01-27 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ditaresource', '0006_tutoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoravailability',
            name='timeEnd',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='tutoravailability',
            name='timeStart',
            field=models.TimeField(default=datetime.time(11, 8, 25, 898441)),
        ),
    ]
