# Generated by Django 5.0.1 on 2024-01-27 12:30

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ditaresource', '0007_tutoravailability_timeend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unitss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=15)),
                ('unitCode', models.CharField(max_length=10)),
                ('unitName', models.CharField(max_length=29)),
            ],
        ),
        migrations.AlterField(
            model_name='tutoravailability',
            name='timeStart',
            field=models.TimeField(default=datetime.time(12, 30, 15, 260246)),
        ),
        migrations.CreateModel(
            name='ClientTutorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ditaresource.client')),
                ('tutorAvailability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ditaresource.tutoravailability')),
            ],
        ),
        migrations.CreateModel(
            name='TutorUnitss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ditaresource.tutor')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ditaresource.unitss')),
            ],
        ),
    ]
